# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-21 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('qualification', models.CharField(choices=[('------', ''), ('B.E.', 'B.E.'), ('MBA', 'MBA'), ('MCA', 'MCA')], max_length=4)),
                ('licen', models.BooleanField(default=False)),
            ],
        ),
    ]
