# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-21 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userform',
            name='gender',
            field=models.BooleanField(choices=[('M', 'Male'), ('F', 'Female')], default=False, max_length=2),
        ),
        migrations.AlterField(
            model_name='userform',
            name='qualification',
            field=models.CharField(choices=[('choice', '--Choose-'), ('B.E.', 'B.E.'), ('MBA', 'MBA'), ('MCA', 'MCA')], max_length=4),
        ),
    ]
