# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-21 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userform', '0002_auto_20170921_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=2),
        ),
    ]
